.TH nicko 1 "15 July 2018"
.SH NAME
.B nicko
\- A dead simple tool to identify popular file types.
.SH SYNOPSIS
.B nicko
[OPTIONS] FILE ...
.SH DESCRIPTION

.TP
\fB\-n \-\-name
Print file name as well.
.TP
\fB\-t \-\-type
Show only file type without file name.
.TP
\fB\-q \-\-quiet
Do not display output.
.TP
\fB\-g \-\-group
Print group instead of type.
.TP
\fB\-v \-\-version\fR
Show version and build information.
.TP
\fB\-h \-\-help\fR
Show short help message.
.SH AUTHOR
Written by bindh3x <nicko@bindh3x.io>
